"""init

Revision ID: 24552384c74b
Revises: 
Create Date: 2026-05-11 13:32:50.238938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24552384c74b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('day', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('career', sa.String(length=200), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('speaker_email', sa.String(length=200), nullable=True),
    sa.Column('speaker_phone', sa.String(length=50), nullable=True),
    sa.Column('academic_degree', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=200), nullable=True),
    sa.Column('social', sa.String(length=300), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('actividad')
    # ### end Alembic commands ###
